In [19]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import tensorflow.keras.backend as K
from keras.models import Sequential
from keras.layers import Dense, InputLayer
from keras.callbacks import Callback

class CustomLoss(tf.keras.losses.Loss):
    def __init__(self,shape,z,x0,name="custom_loss"):
        super().__init__(name=name)
        self.shape = shape
        self.z = tf.constant(z, dtype=tf.float32)
        self.x0 = tf.constant(x0, dtype=tf.float32)
        

    def call(self, y_true, y_pred):
        # Operação matricial: y_true @ M
        aux = tf.reshape(y_true, self.shape)
        u = aux[0]
        p = aux[1:]
        p_with_x0 = tf.concat([self.x0, p], axis=1)

        return u,p_with_x0

In [6]:
new_shape = [5, 2] 
z = [1,2,3,4,5,6,7,8,9,10]
y_true_example = tf.constant(z, dtype=tf.float32)
custom_loss = CustomLoss(new_shape)
reshaped_y_true = custom_loss.call(y_true_example, y_true_example)

In [20]:
nTimeDisc = 10
nSpaceDisc = 3
TimeDisc = np.linspace(0,1,nTimeDisc)
SpaceDisc = np.linspace(0,5,nSpaceDisc)
shape = [nSpaceDisc,nTimeDisc]
exemplo = [1,1,1,1,1,1,1,1,1,1,1,2,3,4,5,6,7,8,9,10,10,20,30,40,50,60,70,80,90,100]
y_true_example = tf.constant(exemplo, dtype=tf.float32)
custom_loss = CustomLoss(shape,[],[0,0])
aux = custom_loss.call(y_true_example, y_true_example)

2024-05-31 18:03:01.053383: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: INVALID_ARGUMENT: ConcatOp : Expected concatenating dimensions in the range [-1, 1), but got 1


InvalidArgumentError: {{function_node __wrapped__ConcatV2_N_2_device_/job:localhost/replica:0/task:0/device:CPU:0}} ConcatOp : Expected concatenating dimensions in the range [-1, 1), but got 1 [Op:ConcatV2] name: concat

In [15]:
u = aux[0]
z = aux[1:]
z

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.]],
      dtype=float32)>

<tf.Tensor: shape=(3, 10), dtype=float32, numpy=
array([[  1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.],
       [  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.]],
      dtype=float32)>

In [12]:
u

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)>